### ISSUE TITLE
Cleanup and finalize the fail/exit/abort methods

### ISSUE THREAD

**Issue by mtrunkat** [apify/apify-sdk-js#162]
### Feature

- `actor.fail()` is just a wrapper around `actor.exit()` providing a default exit code 1, but this behavior is not documented
- `actor.exit(statusMessage)` should save the status to the cloud message prior to the process exit using `Actor.setStatusMesage` with `isStatusMessageTerminal` set to true
- `actor.abort()` is saving status message but without the `isStatusMessageTerminal` set to true

### Motivation

To comply with the specification.

**Comment by B4nan** [comment]
cc @barjin, this is basically all done with your latest changes, but its true we are missing some notes at least in the jsdoc of those methods
