### ISSUE TITLE
Better error handling and logging for Apify proxy configuration

### ISSUE THREAD

**Issue by HonzaTuron** [apify/apify-sdk-js#262]
### Feature

We want to change the behavior of the instance of `Actor.createProxyConfiguration`

Current behavior:
-  throws an error if a user is not logged in (doesn't provide the proxy password)
- throws an error if the user doesn't have access to the Apify proxy

Suggested change:
We would like to just print a warning to the console instead (or create some safer `createProxyConfiguration`) on the local environment. The Apify proxy just wouldn't be used at all, the configuration would do nothing.

Also, we proposed adding an additional warning - if the user has access to the Apify proxy but can't use it locally (this must be explained properly - free plan users).

We also propose an improved copy for the original error.
- It must be clear from the first error user can simply use CLI `apify login` cmd to get the proxy password.

### Motivation

Make Apify templates as seamless as possible. Now, a developer has to think about where it can be run and catch different errors. It is not clear from the error what to do and we have feedback from real users that struggled with this for quite some time.

### Ideal solution or implementation, and any additional constraints

Make `Actor.createProxyConfiguration` with warnings instead of error for local environment.

**Comment by jbartadev** [comment]
CC @mtrunkat @B4nan

**Comment by mtrunkat** [comment]
Yes, ideally, everybody should use a proxy to have consistent behavior when running locally and when on the platform. But this leads to every new user who starts developing locally getting 2 errors:
1. Access denied ➡️  you need to sign in
2. Cannot use Apify Proxy local as on the free account

Instead, we should optimize for a quick win in the onboarding flow, and new users should be able to run every template (if possible) without signing in and having proxy access.

So:
- If user is signed in and has external access, then use a proxy
- If not signed or without access, then skip proxy usage, but clearly and visibly state this in the log

@B4nan could you please prioritize this? There is a large potential as, at the moment every new user gets and error and then another error. So we believe this may largely improve onboarding.

**Comment by B4nan** [comment]
Released as [v3.1.15](https://github.com/apify/apify-sdk-js/releases/tag/apify%403.1.15), tried to use a fresh playwright template and it seems to be working fine.
