### ISSUE TITLE
Add SDK version to Client user agent

### ISSUE THREAD

**Issue by mnmkng** [apify/apify-sdk-js#331]
### Feature

It would be great if we could add information about SDK to Apify Client calls that are being called with Apify SDK and not Client directly.

### Motivation

We would like to understand which Actor runs on the platform are triggered from Client (external calls) or SDK (implies either some Actor implementation, or perhaps a wrong selection of library). The user agents are already tracked on platform, so no changes needed there.

### Ideal solution or implementation, and any additional constraints

The best way to do that would probably be by adding SDK version to the Client user agent.

### Other context

If this is accepted, it might be worth adding even more info, like Crawlee version, if called from Crawlee.

**Comment by mnmkng** [comment]
It's not super high prio TBH. But it would be nice if it didn't just die somewhere in icebox 😄

**Comment by B4nan** [comment]
So it actually looks like the axios upgrade I did some time ago broke the custom UA completely, we didn't have any tests for this. It only works when I disable the request interceptors.
