### ISSUE TITLE
`getTotalCount()` after `Actor.openRequestQueue` always returns 0

### ISSUE THREAD

**Issue by HonzaTuron** [apify/apify-sdk-js#337]
### Issue description

When Run is resurrected, `await Actor.apifyClient.requestQueue(unnamedRequestQueueId).get()` is wrong because it seems doesn't count unnamed request queues.

See Actor run for details: https://console.apify.com/actors/7GTYYp9dZwfhOlSvB/runs/6RwAfFak6BwqdDfew#log

### Code sample

```TypeScript
const requestQueue = await Actor.apifyClient.requestQueue(unnamedRequestQueueId).get()
```

### Package version

latest

### Node.js version

LTS

**Comment by barjin** [comment]
The `getTotalCount()` value is [calculated](https://github.com/apify/crawlee/blob/1e59f1b53176ec45ad42dbc8590d9f3626debacb/packages/core/src/storages/request_provider.ts#L98) from the number of **enqueued requests** and the **`initialCount`**. 

And while we correctly set the `initialCount` in Crawlee's `RequestQueue.open()` [here](https://github.com/apify/crawlee/blob/1e59f1b53176ec45ad42dbc8590d9f3626debacb/packages/core/src/storages/request_provider.ts#L835), this doesn't happen in the SDK's `openRequestQueue` or `_openStorage`- [missing here](https://github.com/apify/apify-sdk-js/blob/d90cc4fd038efaa226535d05e8f3444d6e555dd8/packages/apify/src/actor.ts#L813).

Tbh, I'm not sure where's the best place to squeeze this in - probably straight in [`openRequestQueue`](https://github.com/apify/apify-sdk-js/blob/d90cc4fd038efaa226535d05e8f3444d6e555dd8/packages/apify/src/actor.ts#L821)? It's IMO smelly, as we'd be injecting a private property (`initialCount`) into Crawlee's `RequestQueue` instance. 

Thoughts @vladfrangu @janbuchar ?

**Comment by B4nan** [comment]
> probably straight in [openRequestQueue](https://github.com/apify/apify-sdk-js/blob/d90cc4fd038efaa226535d05e8f3444d6e555dd8/packages/apify/src/actor.ts#L821)

I'd hotfix it this way, we have too many things in progress and ahead of us, let's not waste too much time on what can be a oneliner.
