### ISSUE TITLE
Flaky implementation some of Actor tests

### ISSUE THREAD

**Issue by drobnikj** [apify/apify-sdk-js#84]
### Issue description

Some of the tests for Actor didn't work correctly, the problem is in mocking getValue method on top of defaultStore. The expect calls are in mock function, but the mock function is never called so the test passed even if there is a bug, see https://github.com/apify/apify-sdk-js/blob/master/test/apify/actor.test.ts#L983 
Plus the test for `Actor.pushData` testing setValue method.

I just discover it during #83, but don't have time to fix it.

### Package version

3.0.2

### Node.js version

all

**Comment by B4nan** [comment]
> The expect calls are in mock function,

This is so common problem, it cought me several times too. Would be great to have some eslint rule for assertions inside async callbacks.

@vladfrangu ptal
